[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pdfjs-dist"]

[[scheduled.functions]]
  path = "check-doepb"
  schedule = "CRON_TZ=America/Fortaleza 40 8 * * *"

[[redirects]]
  from = "/status"
  to = "/.netlify/functions/status"
  status = 200
