[functions]
  node_bundler = "esbuild"
  # evita embutir libs grandes no bundle
  external_node_modules = ["pdfjs-dist", "@netlify/blobs"]

[[redirects]]
  from = "/status"
  to = "/.netlify/functions/status"
  status = 200

[[redirects]]
  from = "/status.json"
  to = "/.netlify/functions/status-json"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/.netlify/functions/admin"
  status = 200

[functions]
directory = "netlify/functions"

[[scheduled.functions]]
name = "check-doepb"
cron = "5 11 * * *"

[[scheduled.functions]]
name = "check-doepb"
cron = "5 14 * * *"

[[scheduled.functions]]
name = "check-doepb"
cron = "5 17 * * *"
